only_rules:
  - closing_brace
  - closure_parameter_position
  - colon
  - comma
  - computed_accessors_order
  - control_statement
  - empty_enum_arguments
  - empty_parameters
  - mark
  - opening_brace
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace

closing_brace: error

closure_parameter_position: error

colon:
  severity: error
  # flexible_right_spacing: true
  # apply_to_dictionaries: false

comma: error

control_statement: error

empty_enum_arguments: error

empty_parameters: error

mark: error

opening_brace:
  severity: error
  allowMultilineFunc: true

trailing_newline: error

trailing_semicolon: error

trailing_whitespace:
  severity: error
  ignores_empty_lines: true
  ignores_comments: true