only_rules:
  - closing_brace
  - closure_parameter_position
  - colon
  - comma
  - computed_accessors_order
  - control_statement
  - deployment_target
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - implicit_getter
  - leading_whitespace
  - mark
  - opening_brace
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace

closing_brace: error

closure_parameter_position: error

colon:
  severity: error
  # flexible_right_spacing: true
  # apply_to_dictionaries: false

comma: error

control_statement: error

deployment_target:
    severity: error
    iOSApplicationExtension_deployment_target: 14.7
    iOS_deployment_target: 14.7

empty_enum_arguments: error

empty_parameters: error

empty_parentheses_with_trailing_closure: error

implicit_getter: error

leading_whitespace: error

mark: error

opening_brace:
  severity: error
  allowMultilineFunc: true

trailing_newline: error

trailing_semicolon: error

trailing_whitespace:
  severity: error
  ignores_empty_lines: true
  ignores_comments: true