only_rules:
  - closing_brace
  - closure_parameter_position
  - colon
  - comma
  - computed_accessors_order
  - control_statement
  - deployment_target
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - implicit_getter
  - leading_whitespace
  - mark
  - multiple_closures_with_trailing_closure
  - no_space_in_method_call
  - opening_brace
  - operator_whitespace
  - orphaned_doc_comment
  - private_over_fileprivate
  - redundant_discardable_let
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - switch_case_alignment
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unavailable_condition
  - unneeded_break_in_switch
  - unused_closure_parameter

closing_brace: error

closure_parameter_position: error

colon:
  severity: error
  # flexible_right_spacing: true
  # apply_to_dictionaries: false

comma: error

control_statement: error

deployment_target:
    severity: error
    iOSApplicationExtension_deployment_target: 14.7
    iOS_deployment_target: 14.7

empty_enum_arguments: error

empty_parameters: error

empty_parentheses_with_trailing_closure: error

implicit_getter: error

leading_whitespace: error

mark: error

multiple_closures_with_trailing_closure: error

no_space_in_method_call: error

opening_brace:
  severity: error
  allowMultilineFunc: true

operator_whitespace: error

orphaned_doc_comment: error

private_over_fileprivate:
  severity: error

redundant_discardable_let: error

redundant_set_access_control: error

redundant_string_enum_value: error

redundant_void_return: error

return_arrow_whitespace: error

switch_case_alignment:
  severity: error

trailing_comma:
  severity: error
  mandatory_comma: false

trailing_newline: error

trailing_semicolon: error

trailing_whitespace:
  severity: error
  ignores_empty_lines: true
  ignores_comments: true

unavailable_condition: error

unneeded_break_in_switch: error

unused_closure_parameter: error
