only_rules:
  # default rules
  - block_based_kvo
  - closing_brace
  - closure_parameter_position
  - colon
  - comma
  - computed_accessors_order
  - control_statement
  - deployment_target
  - discouraged_direct_init
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - implicit_getter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_random
  - mark
  - multiple_closures_with_trailing_closure
  - no_space_in_method_call
  - ns_number_init_as_function_reference
  - opening_brace
  - operator_whitespace
  - orphaned_doc_comment
  - private_over_fileprivate
  - private_unit_test
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - self_in_property_initialization
  - shorthand_operator
  - statement_position
  - switch_case_alignment
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unavailable_condition
  - unneeded_break_in_switch
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return
  # opt-in rules

block_based_kvo: error

closing_brace: error

closure_parameter_position: error

colon:
  severity: error
  # flexible_right_spacing: true
  # apply_to_dictionaries: false

comma: error

control_statement: error

deployment_target:
    severity: error
    iOSApplicationExtension_deployment_target: 14.7
    iOS_deployment_target: 14.7

discouraged_direct_init:
  severity: error

empty_enum_arguments: error

empty_parameters: error

empty_parentheses_with_trailing_closure: error

implicit_getter: error

leading_whitespace: error

legacy_cggeometry_functions: error

legacy_constant: error

legacy_constructor: error

legacy_hashing: error

legacy_nsgeometry_functions: error

legacy_random: error

mark: error

multiple_closures_with_trailing_closure: error

no_space_in_method_call: error

ns_number_init_as_function_reference: error

opening_brace:
  severity: error
  allowMultilineFunc: true

operator_whitespace: error

orphaned_doc_comment: error

private_over_fileprivate:
  severity: error

private_unit_test:
  warning: XCTestCase

protocol_property_accessors_order: error

redundant_discardable_let: error

redundant_optional_initialization: error

redundant_set_access_control: error

redundant_string_enum_value: error

redundant_void_return: error

return_arrow_whitespace: error

self_in_property_initialization: error

shorthand_operator: error

statement_position: 
  statement_mode: default
  severity: error

switch_case_alignment:
  severity: error

syntactic_sugar: error

trailing_comma:
  severity: error
  mandatory_comma: false

trailing_newline: error

trailing_semicolon: error

trailing_whitespace:
  severity: error
  ignores_empty_lines: true
  ignores_comments: true

unavailable_condition: error

unneeded_break_in_switch: error

unused_closure_parameter: error

unused_enumerated: error

unused_optional_binding:
  severity: error
  ignore_optional_try: false

unused_setter_value: error

vertical_parameter_alignment: error

vertical_whitespace:
  severity: error
  max_empty_lines: 1

void_return: error
