#!/bin/bash

set -eo pipefail

realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

SCRIPT_PATH=`realpath "$0"`
SCRIPT_DIR=`dirname "$SCRIPT_PATH"`
DESTINATION_DIR="$SCRIPT_DIR/../Bundled/ONNXRuntime"
HASH_FILE="$DESTINATION_DIR/onnxruntime_hash.txt"

ONNX_RUNTIME_VERSION="1.26.0"
ARCHIVE_SHA256="08502ec252f6f03ebee6e729cbe0525c777b47daa76d3bc8c04bba82201d8a36"
DOWNLOAD_URL="https://download.onnxruntime.ai/pod-archive-onnxruntime-c-${ONNX_RUNTIME_VERSION}.zip"
CURRENT_HASH="${ONNX_RUNTIME_VERSION}:${ARCHIVE_SHA256}"

if [ -d "$DESTINATION_DIR" ]; then
    if [ -f "$HASH_FILE" ]; then
        CACHED_HASH=`cat "$HASH_FILE"`
    else
        CACHED_HASH=0
    fi

    if [ "$CACHED_HASH" == "$CURRENT_HASH" ] \
        && [ -d "$DESTINATION_DIR/onnxruntime.xcframework" ] \
        && [ -d "$DESTINATION_DIR/Headers" ]; then
        exit
    else
        rm -rf "$DESTINATION_DIR"
    fi
fi

TMP_DIR=$(mktemp -d)
echo "Created temp dir: $TMP_DIR"

cleanup() {
    rm -rf "$TMP_DIR"
}
trap cleanup EXIT

echo "Downloading ONNX Runtime $ONNX_RUNTIME_VERSION from: $DOWNLOAD_URL"
curl -L "$DOWNLOAD_URL" -o "$TMP_DIR/onnxruntime.zip"

ACTUAL_SHA256=`shasum -a 256 "$TMP_DIR/onnxruntime.zip" | awk '{ print $1 }'`
if [ "$ACTUAL_SHA256" != "$ARCHIVE_SHA256" ]; then
    echo "Error: ONNX Runtime archive SHA-256 mismatch."
    echo "Expected: $ARCHIVE_SHA256"
    echo "Actual:   $ACTUAL_SHA256"
    exit 1
fi

echo "Unzipping..."
unzip -q "$TMP_DIR/onnxruntime.zip" -d "$TMP_DIR/build"

FRAMEWORK_DIR=`find "$TMP_DIR/build" -type d -name "onnxruntime.xcframework" -print -quit`
if [ -z "$FRAMEWORK_DIR" ]; then
    echo "Error: onnxruntime.xcframework not found in the archive."
    exit 1
fi

HEADER_DIR=`find "$FRAMEWORK_DIR" -type d -path "*/onnxruntime.framework/Headers" -print -quit`
if [ -z "$HEADER_DIR" ]; then
    echo "Error: ONNX Runtime headers not found in the archive."
    exit 1
fi

mkdir -p "$DESTINATION_DIR"
cp -R "$FRAMEWORK_DIR" "$DESTINATION_DIR/onnxruntime.xcframework"
cp -R "$HEADER_DIR" "$DESTINATION_DIR/Headers"

LICENSE_FILE=`find "$TMP_DIR/build" -type f -name "LICENSE" -print -quit`
if [ -n "$LICENSE_FILE" ]; then
    cp "$LICENSE_FILE" "$DESTINATION_DIR/LICENSE"
fi

cat > "$DESTINATION_DIR/README.md" <<EOF
# ONNX Runtime

This directory is generated by scripts/bundle_onnxruntime.sh and is intentionally gitignored.

Version: \`$ONNX_RUNTIME_VERSION\`

Source podspec: \`onnxruntime-c\`

Archive URL: \`$DOWNLOAD_URL\`

Archive SHA-256:

\`\`\`text
$ARCHIVE_SHA256
\`\`\`

The podspec declares:

- \`vendored_frameworks\`: \`onnxruntime.xcframework\`
- \`libraries\`: \`c++\`
- \`weak_frameworks\`: \`CoreML\`
EOF

echo "$CURRENT_HASH" > "$HASH_FILE"
echo "ONNX Runtime $ONNX_RUNTIME_VERSION installed at $DESTINATION_DIR"
